[[language]]
name = "c"
indent = {tab-width = 8, unit = "        "}

[[language]]
name = "odin"
indent = {tab-width = 8, unit = "        "}

[[language]]
name = "zig"
indent = {tab-width = 8, unit = "        "}
